baseURL = "https://madai.es"
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false

[languages]
    [languages.es]
      disabled = false
      languageCode = 'es'
      languageName = 'ES'
      weight = 1
    [languages.en]
      disabled = false
      languageCode = 'en'
      languageName = 'EN'
      weight = 2
